# Generated by Django 5.0.6 on 2024-05-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
