# Generated by Django 5.0.6 on 2024-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='about me'),
        ),
    ]
